CREATE TABLE `comt_cfg_b` (
  `RID` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '唯一记录号',
  `COMT_ID` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '组件ID',
  `FLD_SN` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '组件字段序号',
  `COMT_FLD_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '组件字段名称',
  `COMT_FLD_CODE` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '组件字段代码',
  `COMT_DSCR` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '组件描述',
  `COMT_WARN` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '组件提示',
  `COMT_TYPE` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1' COMMENT '组件类型 1 input 2 下拉框 3 textarea 4 单选 5 多选',
  `LABL_OCCP_COL` decimal(10,0) DEFAULT NULL COMMENT '标签占用列数',
  `COMT_OCCP_COL` decimal(10,0) DEFAULT NULL COMMENT '组件占用列数',
  `DATA_TYPE` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '1' COMMENT '数据类型 1 str 2 num 31 date 32 datetime 33 time',
  `DATA_SOUC` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '数据来源',
  `DATA_SOUC_URL` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '数据来源URL',
  `MUSTL_FLAG` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '必填标志',
  `READO_FLAG` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '只读标志',
  `DSAB_FLAG` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '禁用标志',
  `SUFX_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '后缀名称',
  `SRCH_FLAG` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '搜索标志',
  `FLDVAL_SETS` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '字段数值集合,[{label:"label1",value:"value1"},{label:"label2",value:"value2"}]',
  `LENG` decimal(10,0) DEFAULT NULL COMMENT '长度',
  `MAX_VAL` decimal(16,2) DEFAULT NULL COMMENT '最大值',
  `MIN_VAL` decimal(16,2) DEFAULT NULL COMMENT '最小值',
  `REGL_EXPR` varchar(200) DEFAULT NULL COMMENT '正则表达式',
  `SYS_NO` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '系统编号',
  `TMPL_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '模板标志，0-不是模板；1-是模板',
  `PLACEHOLDER` varchar(100) DEFAULT NULL COMMENT '占位字符',
  `START_PLACEHOLDER` varchar(50) DEFAULT NULL COMMENT '开始占位字符',
  `END_PLACEHOLDER` varchar(50) DEFAULT NULL COMMENT '结束占位字符',
  `VALI_FLAG` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1' COMMENT '有效标志',
  `INSU_ADMDVS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '所属医保区划',
  `ADMDVS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '医保区划',
  `POOLAREA_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '统筹区编号',
  `CRTER_ID` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建人ID',
  `CRTER_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建人姓名',
  `CRTE_OPTINS_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建机构编号',
  `CRTE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OPTER_ID` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '经办人ID',
  `OPTER_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '经办人姓名',
  `OPTINS_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '经办机构编号',
  `OPT_TIME` datetime DEFAULT NULL COMMENT '经办时间',
  `UPDT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`COMT_ID`) USING BTREE,
  KEY `idx_conl_fld_code` (`COMT_FLD_CODE`),
  KEY `idx_sys_no` (`SYS_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='COMT_CFG_B-组件配置表';

CREATE TABLE `fld_cfg_b` (
  `RID` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '唯一记录号',
  `FLD_ID` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '字段ID',
  `FLD_CODE` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '字段代码',
  `FLD_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '字段名称',
  `SYS_NO` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '系统编号',
  `VALI_FLAG` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1' COMMENT '有效标志',
  `INSU_ADMDVS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '所属医保区划',
  `ADMDVS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '医保区划',
  `POOLAREA_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '统筹区编号',
  `CRTER_ID` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建人ID',
  `CRTER_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建人姓名',
  `CRTE_OPTINS_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建机构编号',
  `CRTE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OPTER_ID` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '经办人ID',
  `OPTER_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '经办人姓名',
  `OPTINS_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '经办机构编号',
  `OPT_TIME` datetime DEFAULT NULL COMMENT '经办时间',
  `UPDT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`FLD_ID`) USING BTREE,
  KEY `idx_fld_code` (`FLD_CODE`),
  KEY `idx_fld_name` (`FLD_NAME`),
  KEY `idx_sys_no` (`SYS_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='FLD_CFG_B-字段配置表';

CREATE TABLE `form_cfg_b` (
  `RID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '唯一记录号',
  `FORM_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单ID',
  `FORM_CODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单代码',
  `FORM_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单名称',
  `FORM_DESC` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '表单描述',
  `FORM_COL` decimal(10,0) DEFAULT NULL COMMENT '表单列数',
  `TTL_WID` decimal(10,0) DEFAULT NULL COMMENT '标题宽度',
  `TMPL_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '模板标志，0-不是模板；1-是模板',
  `VALI_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '有效标志',
  `INSU_ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '所属医保区划',
  `ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '医保区划',
  `POOLAREA_NO` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '统筹区编号',
  `CRTER_ID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人ID',
  `CRTER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人姓名',
  `CRTE_OPTINS_NO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建机构编号',
  `CRTE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OPTER_ID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '经办人ID',
  `OPTER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '经办人姓名',
  `OPTINS_NO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '经办机构编号',
  `OPT_TIME` datetime DEFAULT NULL COMMENT '经办时间',
  `UPDT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`FORM_ID`) USING BTREE,
  KEY `idx_form_code` (`FORM_CODE`),
  KEY `idx_form_name` (`FORM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='FORM_CFG_B-表单配置表';

CREATE TABLE `form_cfg_para_b` (
  `RID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '唯一记录号',
  `PARA_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '参数ID',
  `FORM_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单ID',
  `PARA_SEQ` int DEFAULT '0' COMMENT '参数顺序号',
  `PARA_NAME` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '参数名称',
  `PARAVAL` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '参数值',
  `TMPL_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '模板标志，0-不是模板；1-是模板',
  `VALI_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '有效标志',
  `INSU_ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '所属医保区划',
  `ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '医保区划',
  `POOLAREA_NO` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '统筹区编号',
  `CRTER_ID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人ID',
  `CRTER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人姓名',
  `CRTE_OPTINS_NO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建机构编号',
  `CRTE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`PARA_ID`) USING BTREE,
  KEY `idx_form_id` (`FORM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='FORM_CFG_PARA_B-表单配置参数表';

CREATE TABLE `form_inst_b` (
  `RID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '唯一记录号',
  `FORM_INST_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单实例ID',
  `BIZ_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务ID',
  `FORM_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单ID',
  `FORM_CODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单代码',
  `FORM_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单名称',
  `VALI_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '有效标志',
  `INSU_ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '所属医保区划',
  `ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '医保区划',
  `POOLAREA_NO` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '统筹区编号',
  `CRTER_ID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人ID',
  `CRTER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人姓名',
  `CRTE_OPTINS_NO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建机构编号',
  `CRTE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OPTER_ID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '经办人ID',
  `OPTER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '经办人姓名',
  `OPTINS_NO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '经办机构编号',
  `OPT_TIME` datetime DEFAULT NULL COMMENT '经办时间',
  `UPDT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`FORM_INST_ID`) USING BTREE,
  KEY `idx_biz_id` (`BIZ_ID`),
  KEY `idx_form_id` (`FORM_ID`),
  KEY `idx_form_code` (`FORM_CODE`),
  KEY `idx_form_name` (`FORM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='FORM_INST_B-表单实例表';

CREATE TABLE `form_inst_para_b` (
  `RID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '唯一记录号',
  `FORM_INST_PARA_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '表单实例参数ID',
  `FORM_INST_ID` varchar(40) COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单实例ID',
  `BIZ_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务ID',
  `FORM_ID` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单ID',
  `PARA_SEQ` int DEFAULT '0' COMMENT '参数顺序号',
  `PARA_NAME` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '参数名称',
  `PARAVAL` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '参数值',
  `VALI_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '有效标志',
  `INSU_ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '所属医保区划',
  `ADMDVS` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '医保区划',
  `POOLAREA_NO` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '统筹区编号',
  `CRTER_ID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人ID',
  `CRTER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人姓名',
  `CRTE_OPTINS_NO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建机构编号',
  `CRTE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`FORM_INST_PARA_ID`) USING BTREE,
  KEY `idx_biz_id` (`BIZ_ID`),
  KEY `idx_form_id` (`FORM_ID`) /*!80000 INVISIBLE */,
  KEY `idx_form_inst_id` (`FORM_INST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='FORM_INST_PARA_B-表单实例参数表';
